In [3]:
import numpy as np
np.set_printoptions(suppress=True)

In [4]:
A = np.vander(np.array([1,2,3,4,5]))
print(A)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [5]:
Q1, R1 = np.linalg.qr(A)
B1 = Q1.T @ A @ Q1
print(B1)

[[  11.70370362   95.94985219 -391.83817342  548.76240376  141.99011309]
 [   3.74545605   11.42886867  -12.06749667   -4.41288385   -6.03073889]
 [  -1.60429851   -1.31349271   -0.19198933    0.15806735   -0.47209789]
 [   0.64226745    0.00069666    0.06699352    0.05543297   -0.06265891]
 [   0.0579779    -0.02211493   -0.00958549   -0.00507957    0.00398406]]


In [6]:
Q2, R2 = np.linalg.qr(B1)
B2 = Q2.T @ B1 @ Q2
print(B2)

[[ 115.68622618  370.62194891 -452.21166965  270.56856131  -61.22404307]
 [ -31.7512938  -117.64692367  157.63938398 -102.58204324   25.34084046]
 [  -3.74105044  -15.14265967   26.48924234  -21.88724748    6.74361227]
 [  -0.09133312   -0.39278026    0.8289485    -1.569848      0.87873481]
 [  -0.00019546   -0.00088038    0.00212591   -0.00624528    0.04130314]]


In [10]:
for i in range(10):
    Q, R = np.linalg.qr(B2)
    B2 = Q.T @ B2 @ Q

In [11]:
print(B2)

[[  45.96412364  333.07086454 -514.75546618  307.71949702  -66.79344218]
 [  -0.00082962  -28.94739072   62.92350346  -47.45384027   12.68847997]
 [  -0.           -0.            6.79538792   -9.37453655    3.58763723]
 [  -0.           -0.            0.           -0.84961948    0.64728609]
 [  -0.           -0.            0.           -0.            0.03749864]]


In [9]:
np.linalg.eigvals(B2)

array([ 45.96043479, -28.94370187,   6.79538792,  -0.84961948,
         0.03749864])

In [12]:
A0 = A
for i in range(20):
    Q,R = np.linalg.qr(A0)
    A0 = R @ Q

In [13]:
print(A0)

[[  45.96973691  333.06960194 -514.75440564  307.71869722  -66.79322833]
 [  -0.00209222  -28.953004     62.93217873  -47.45902632   12.68960565]
 [  -0.           -0.            6.79538792   -9.37453655    3.58763723]
 [  -0.           -0.            0.           -0.84961948    0.64728609]
 [  -0.           -0.            0.           -0.            0.03749864]]


In [14]:
np.linalg.eigvals(A)

array([ 45.96043479, -28.94370187,   6.79538792,  -0.84961948,
         0.03749864])