In [10]:
import numpy as np
np.set_printoptions(suppress=True)

In [11]:
A = np.array([[1,2,3],[4,5,6]])
print('A:\n', A)

A:
 [[1 2 3]
 [4 5 6]]


In [12]:
S = A.T @ A
print('S:\n', S)

S:
 [[17 22 27]
 [22 29 36]
 [27 36 45]]


In [14]:
S0 = S
for i in range(10):
    [Q,R] = np.linalg.qr(S0)
    S0 = R @ Q 

In [17]:
print('Autovalores da matriz S:\n', S0)

Autovalores da matriz S:
 [[90.40267253 -0.          0.        ]
 [ 0.          0.59732747  0.        ]
 [ 0.          0.          0.        ]]


In [18]:
sigma1 = np.sqrt(S0[0,0])
sigma2 = np.sqrt(S0[1,1])

print('Valores singulares da matriz A: ', sigma1, sigma2)

Valores singulares da matriz A:  9.508032000695723 0.7728696356734887


In [19]:
U, Sigma, VT = np.linalg.svd(A)
print(Sigma)

[9.508032   0.77286964]
